### ISSUE TITLE
Code can't be minified (and won't work in strict-di mode)

### ISSUE THREAD

**Issue by alonbardavid** [marklagendijk/ui-router.stateHelper#11]
The original source-code (not the minified one) doesn't use the bracket or inject notation to declare the stateHelper provider, so it can't be directly minified.

Also it'll fail if using the new strict-di mode introduced in 1.3

**Comment by paradox41** [comment]
It should be noted that the lack of DI friendliness on the non-minified version makes NPM installing a bit of a hassle, since it looks like npm wants to use the non-minified version by default.

Just FYI.
