### ISSUE TITLE
Please add to npm registry

### ISSUE THREAD

**Issue by kburson** [marklagendijk/ui-router.stateHelper#17]
The Angular team is moving towards use of npm over bower. To this intent all the angular modules are available from npm.  NPM has proven to be a more stable and full featured package manager that overshadows bower.  I see the 'components' is on the rise as well.  

Please add this module to the npm registry so we can reference it using npm and not have duplication in a bower_components local install as well.

Thanks.

**Comment by marklagendijk** [comment]
Done :).
